buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.application'

android {
    namespace 'com.androhub'
    compileSdkVersion 4 // API 4 (Donut) para o AAPT2 compilar sem erros de manifesto

    defaultConfig {
        applicationId "com.androhub"
        minSdkVersion 3     // Android 1.5 (Cupcake)
        targetSdkVersion 3  // Força o comportamento do Cupcake
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }
}